site:
  baseline: deep learning
  baseurl: /
  canonicalurl: true
  date:
    format: j F Y
    timezone: Europe/Paris
  description: Novosti iz deep learning svijeta i detalji o DI study grupi u Puli
  netlify:
    cms:
      path: admin
      version: latest
    identity:
      version: v1
  pagination:
    max: 5
    path: page
  title: Umjetna inteligencija
theme: hyde
